jobs:
- name: test_cloudops-terraform_dev
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: true
  - get: "terraform_docker_image"
  - task: "plan"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: dev
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make plan
- name: apply_cloudops-terraform_dev
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    passed: ["test_cloudops-terraform_dev"]
    trigger: true
  - get: "terraform_docker_image"
  - task: "apply"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: dev
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make apply
- name: test_cloudops-terraform_staging
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: true
    passed: ["apply_cloudops-terraform_dev"]
  - get: "terraform_docker_image"
  - task: "plan"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: staging
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make plan
- name: apply_cloudops-terraform_staging
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    passed: ["test_cloudops-terraform_staging"]
    trigger: true
  - get: "terraform_docker_image"
  - task: "apply"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: staging
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make apply
- name: test_cloudops-terraform_management
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: true
  - get: "terraform_docker_image"
  - task: "plan"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: management
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make plan
- name: apply_cloudops-terraform_management
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: true
    passed: ["test_cloudops-terraform_management"]
  - get: "terraform_docker_image"
  - task: "apply"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: management
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make apply
- name: test_cloudops-terraform_prod
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: true
    passed: ["apply_cloudops-terraform_staging"]
  - get: "terraform_docker_image"
  - task: "plan"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: prod
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make plan
- name: apply_cloudops-terraform_prod
  serial: true
  public: true
  plan:
  - get: "git_repo_cloudops-terraform"
    trigger: false
    passed: ["test_cloudops-terraform_prod"]
  - get: "terraform_docker_image"
  - task: "apply"
    image: "terraform_docker_image"
    config:
      platform: linux
      inputs:
      - name: "git_repo_cloudops-terraform"
      params:
        APP_ENV: prod
        GITHUB_PRIVATE_KEY: ((github_private_key))
      run:
        dir: git_repo_cloudops-terraform
        path: sh
        args:
          - "-ec"
          - |
            mkdir ~/.ssh
            echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 0600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
            apk add make
            make apply

resources:
- name: "terraform_docker_image"
  type: docker-image
  source:
    repository: "hashicorp/terraform"
    tag: "0.11.14"

- name: "git_repo_cloudops-terraform"
  type: "git"
  source:
    uri: "git@github.com:River-Island/cloudops-terraform.git"
    branch: "master"
    private_key: ((github_private_key))
